### ISSUE TITLE
check_usage: Convert local times to UTC before passing to REST API

### ISSUE THREAD

**Issue by matthew-li** [ucb-rit/slurm-banking-utilities#6]
A user raised an issue in which there was a discrepancy in the value returned by `check_usage.sh` vs. the value displayed on MyBRC.

The reason for this is that `check_usage.sh` includes jobs starting 7 hours earlier than it should (the difference between UTC and local time), causing the total usage returned to be higher than the true value.

The date given by the user should be interpreted as a local `datetime` and then converted to UTC before being passed to the REST API.

**Comment by ViRu-ThE-ViRuS** [comment]
okay, pushed changes so that if user sets start time to `2022-08-01` it is treated as local time, and API is sent `2022-08-01T07:00:00Z` and that is also what is printed in the output. 

also now with `check_usage.sh -a <acct_name> -s 2022-08-01`, the first line of output will be:
`Usage for ACCOUNT <acct-name> [2022-08-01T07:00:00Z, ...]: ....`
- ie. all times in output will be UTC
